---
blank_issues_enabled: false
contact_links:
  -
    about: Visit our Discussions page
    name: ğŸ’¡ Feature requests
    url: hhttps://github.com/openqda/feedback/discussions/categories/ideas
  -
    about: Ask a question or for help
    name: â“ Question
    url: https://github.com/openqda/feedback/discussions/categories/q-a
